import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BrandLive | Virtual Events Production</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <svg height="100vh" width="100vw">
          <circle cx="0%" cy="75%" r="60" fill="#5AE4FF" />
          <circle cx="5%" cy="75%" r="24" fill="rgba(255, 125, 248, 1)" />
        </svg>
        <header className={styles.header}>
          <div className={styles.headerBox}>
            <nav className={styles.navbarSectionContainer}>
              <div className={styles.navbarContainer}>
                <div className={styles.logo}>
                  <Image src="/image.png" alt="logo" width={150} height={65} />
                </div>
                <div className={styles.list}>
                  <ul className={styles.ul}>
                    <li>Products</li>
                    <li>Pricing</li>
                    <li>Company</li>
                    <li>Customers</li>
                    <li>Productions</li>
                    <li>Agency Partners</li>
                    <li>Log In</li>

                    <li id={styles.menuRequest}>
                      <div className={styles.border}>
                        <div className={styles.text}>
                          <a>Request Demo</a>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </header>
        <div className={styles.mainContainer}>
          <div className={styles.title}>
            <h1>Virtual, done right.</h1>
          </div>
          <div className={styles.description}>
            <h2>Helping the boldest brands cut through the noise</h2>
          </div>
          <div>
            <ul className={styles.sponsersList}>
              <li>
                {" "}
                <Image src="/levis.svg" alt="adidas" height={100} width={100} />
              </li>
              <li>
                {" "}
                <Image
                  src="/adidas.svg"
                  alt="adidas"
                  height={100}
                  width={100}
                />
              </li>
              <li>
                {" "}
                <Image
                  src="/logo_meredith.svg"
                  alt="adidas"
                  height={100}
                  width={100}
                />
              </li>
              <li>
                {" "}
                <Image src="/gopro.svg" alt="adidas" height={100} width={100} />
              </li>
              <li>
                <Image
                  src="/logo_kohler.svg"
                  alt="adidas"
                  height={100}
                  width={100}
                />
              </li>
              <li>
                <Image
                  src="/herbalife.svg"
                  alt="adidas"
                  height={100}
                  width={100}
                />
              </li>
              <li>
                <Image
                  src="/adidas.svg"
                  alt="adidas"
                  height={100}
                  width={100}
                />
              </li>
            </ul>
          </div>
          <div className={styles.bannerContainer}>
            <div className={styles.fastCompany}>Fast Company</div>
            <div className={styles.bannerText}>
              BrandLive named the #1 most innovative company for live events.
            </div>
            <li id={styles.watchNow}>
              <div className={styles.borderWatch}>
                <div className={styles.textWatch}>
                  <a>Watch Now</a>
                </div>
              </div>
            </li>
          </div>
        </div>
      </main>
    </div>
  );
}
